### PR TITLE
Add misspell linter

### PR DESCRIPTION
**Pull request by pellared**
## Why

> Why this pull request was created? Explain the problem that this pull request is trying to solve.

[Go Report Card](https://goreportcard.com/report/github.com/goyek/goyek) detected a typo.

## What

> What does this pull request contain? Explain what is this pull request changing.

- Add `misspell` linter to the build pipeline - it works better than the one embedded in `golangci-lint` and also detects typos e.g. in Markdown files
- Fix typo

## Checklist

- [x] `CHANGELOG.md` is updated. n/a
- [x] `README.md` is updated. n/a
- [x] The code changes follow [Effective Go](https://golang.org/doc/effective_go).

### CODE REVIEW

**Comment by dertseha** [comment]
Curious that the same linter needs to be run explicitly. Could this be because of filters in `golangci-lint`?
Apart from that: How about making two private tasks `misspell` and `golangci-lint` which are both run by the public task `lint`?

**Comment by pellared** [comment]
> Curious that the same linter needs to be run explicitly. Could this be because of filters in `golangci-lint`?

AFAIK filters and it only checks Go code

> Apart from that: How about making two private tasks `misspell` and `golangci-lint` which are both run by the public task `lint`?

Good idea. I will do that

**Review by dertseha — APPROVED** [review]
Cool, thank you.

**Comment by pellared** [comment]
This is funny 😄 

image

**Pull request merged**
