### PR TITLE
Update wrapper scripts in README.md

### PR DESCRIPTION
**Pull request by pellared**
## Why

> Why this pull request was created? Explain the problem that this pull request is trying to solve.

`README.md` has not up-to-date wrapper scripts.

## What

> What does this pull request contain? Explain what is this pull request changing.

Update wrapper scripts in `README.md`.

## Checklist

- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated.
- [x] The code changes follow [Effective Go](https://golang.org/doc/effective_go).

### CODE REVIEW

**Comment by dertseha** [comment]
The section should have a description that the parameter needs to be registered for this combination to work.
The example above in the file does not use it (doing a manual `..`) - so it might be confusing if I were to assume that they were compatible.

**Comment by pellared** [comment]
> The section should have a description that the parameter needs to be registered for this combination to work.
> The example above in the file does not use it (doing a manual `..`) - so it might be confusing if I were to assume that they were compatible.

I am not sure if I follow. Does it address your comment https://github.com/goyek/goyek/pull/79/commits/32e87188be6833df26657a85c3514ad7ce66f388 ?

**Comment by pellared** [comment]
@dertseha Can you double-check this PR, please?

**Comment by dertseha** [comment]
Wait, if the working directory parameter is not registered by default, then the script's use of `-wd` will not work with the provided sample.
That's what I originally meant: The scripts, if they are meant to use the `-wd` parameter, require that the build script registers the parameter. The sample above does not register this parameter, so it's not compatible with the scripts.
This is fine, as the example (presumably) should show the most simplest case. Yet the description for the scripts should state that they need the parameter to work.

**Comment by pellared** [comment]
> Wait, if the working directory parameter is not registered by default, then the script's use of `-wd` will not work with the provided sample.
> That's what I originally meant: The scripts, if they are meant to use the `-wd` parameter, require that the build script registers the parameter. The sample above does not register this parameter, so it's not compatible with the scripts.
> This is fine, as the example (presumably) should show the most simplest case. Yet the description for the scripts should state that they need the parameter to work.

The -wd parameter is out-of-the-box

**Review by dertseha — APPROVED** [review]
Right - `-wd` is registered by default - I forgot.
Thank you -- all fine now.

**Pull request merged**
